### ISSUE TITLE
Generalize computation of area weights based on actual latitudes

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#123]
Currently the area weights are [computed based on a latitude coordinate](https://github.com/ai2cm/full-model/blob/2fd21f6010e3d88ff7855538c508beabd88b911f/fme/fme/fcn_training/train.py#L597C13-L600) that is computed from the length of the latitude dimension, and which is assumed to be "equiangular" (i.e. evenly spaced latitude circles). We may switch to using a gauss-legendre grid (with unevenly spaced latitude circles) so we should not have this hard-coded assumption about the latitude coordinate. Since our training dataset has a latitude coordinate, we should pass it along from the data loader.

**Comment by mcgibbon** [comment]
We may be able to pass along latitude, but we may run into issues because its shape won't be the same as other tensors. Is gridcell area available in the dataset/can we get it in there? Another way I can see doing it is to add a configuration option for the aggregators/diagnostics. In practice we'll just move over to always having a gaussian grid, but it would be nice to have a flag to swap it back if needed.

**Comment by oliverwm1** [comment]
I don't see why the different shape would be an issue... we don't need to pack the latitude variable, right?

It's a good idea to add an area variable to our dataset, we can start doing this for future datasets.

Nevertheless, even if the data has the area variable, there are other things we might want to use the latitude for (specifically, making sure the inference output netCDF has a proper latitude coordinate).
