### ISSUE TITLE
Run, post-process and upload data from new ensemble training runs

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#133]
See details here: https://docs.google.com/document/d/1jQ-LhtNMnxWF9C-oQgfXTcM2GpN3AEZEK9001mEfYl8/edit

**Comment by spencerkclark** [comment]
This is now complete.  The post-processed data from all of the ensemble members can be found at the following paths, with `${ENSEMBLE_MEMBER}` taking on the values between `0001` and `0011`:

- `gs://vcm-ml-raw-flexible-retention/2023-07-08-C96-FME-reference-ensemble/regridded-zarrs/gaussian_grid_180_by_360/ic_${ENSEMBLE_MEMBER}/fluxes_2d.zarr`
- `gs://vcm-ml-raw-flexible-retention/2023-07-08-C96-FME-reference-ensemble/regridded-zarrs/gaussian_grid_180_by_360/ic_${ENSEMBLE_MEMBER}/fourcastnet_vanilla.zarr`
- `gs://vcm-ml-raw-flexible-retention/2023-07-08-C96-FME-reference-ensemble/regridded-zarrs/gaussian_grid_180_by_360/ic_${ENSEMBLE_MEMBER}/full_state.zarr`
- `gs://vcm-ml-raw-flexible-retention/2023-07-08-C96-FME-reference-ensemble/regridded-zarrs/gaussian_grid_180_by_360/ic_${ENSEMBLE_MEMBER}/tendencies_3d.zarr`

All variables were regridded to a 180x360 Gaussian grid and (with the exception of `"land_sea_mask"`) were filtered with a spherical harmonic transform roundtrip, assuming a `"legendre-gauss"` grid before being combined into zarr stores.

The log files and raw C96 cubed sphere history and restart files from all segments of these runs are archived on tape at GFDL: 
- `gfdl:/archive/Spencer.Clark/2023-06-30-C96-FME-reference-simulations/ic_${ENSEMBLE_MEMBER}/ascii`
- `gfdl:/archive/Spencer.Clark/2023-06-30-C96-FME-reference-simulations/ic_${ENSEMBLE_MEMBER}/history`
- `gfdl:/archive/Spencer.Clark/2023-06-30-C96-FME-reference-simulations/ic_${ENSEMBLE_MEMBER}/restart`

in case we want to revisit the post-processing of the data for any variables of these runs at any point later.  For example, I am currently running a workflow to generate ocean, land, and sea-ice fraction data from these runs, since conservatively regridding the raw categorical-valued `"land_sea_mask"` is somewhat ill-posed ([notebook](https://github.com/ai2cm/explore/blob/master/spencerc/2023-07-06-regridding-the-land-sea-mask.ipynb)); I will post the paths to this data shortly.

**Comment by spencerkclark** [comment]
The surface type encoding workflow is complete and the surface type fractions can be found in the following stores (as the metadata in the datasets note, no spherical harmonic transform roundtrip was applied to these variables):

- `gs://vcm-ml-raw-flexible-retention/2023-07-08-C96-FME-reference-ensemble/regridded-zarrs/gaussian_grid_180_by_360/ic_${ENSEMBLE_MEMBER}/encoded_surface_type.zarr`

**Comment by oliverwm1** [comment]
This is great, thanks @spencerkclark! I'll close the issue for now, and we can always reopen if we find problems with the data.
