### ISSUE TITLE
Update the training aggregator to include one-step change in global dry air mass

### ISSUE THREAD

**Issue by gideonite** [ai2cm/ace#147]
The global dry air mass is given by the total air mass minus the water mass. You'll have to back out the total air mass from surface pressure using g to convert, which needs to be the FV3GFS value of 9.80665 (idk what to do about this potentially being different for E3SM). Total global water mass can be derived from TCWV, somehow (you can figure it out based on the units, if this is not straightforward lmk and I can take a stab at it). The goal would be that we have a wandb plot over epoch of the mean and std of the one-step change in global dry air mass over the validation dataset. If the model conserves mass, both would be zero.

**Comment by oliverwm1** [comment]
Couple notes:
1. I would suggest starting with some notebook calculations/plots to make sure you have the equation right before thinking about implementing in the training code.
2. See [this function](https://github.com/ai2cm/full-model/blob/42491fa5fd6df0d04143e4c7fdbf5c1ad331c973/projects/data_process/compute_dataset_fv3gfs.py#L299) which asserts that the global dry air mass tendency is closer to zero in our post-processed data (although note the high absolute tolerance I had to use! I suspect this is coming from the regridding since we've found the budget to be exactly close on the native cubed sphere grid). Note that this function assumes the total water path is already computed, but you'll need to compute it by vertically summing the 8 "specific total water" levels. You can see an example of that calculation in [this notebook](https://github.com/ai2cm/explore/blob/master/oliwm/2023-04-16-fme-analysis/2023-06-02-column-moisture-conservation.ipynb) (e.g. cell 9). An easy way to start might actually be to just copy that notebook and extend it to examine the dry air mass budget (although you'll want to focus on global mean, not column-local).
