### ISSUE TITLE
Wrong nlat/nlon for monkey-patched sfno trans_down and itrans_up

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#155]
Calculation of `modes_lat` and `modes_lon` is incorrect because the `nlat` and `nlon` are swapped. Also, the calculation does not account for `scale_factor` and so would be incorrect for the case of `scale_factor!=1` (which we don't use currently, but might in the future).

See

https://github.com/ai2cm/full-model/blob/cbce52df071fa2c40344bebdba78acacb876948c/fme/fme/core/stepper.py#L138-L143

and

https://github.com/ai2cm/full-model/blob/cbce52df071fa2c40344bebdba78acacb876948c/fme/fme/fcn_training/registry.py#L100-L102

**Comment by mcgibbon** [comment]
I think you're right, given the dims are supposed to be y as the second last dim and x as the last dim. There's a [compensating error in registry.py](https://github.com/ai2cm/full-model/blob/main/fme/fme/fcn_training/registry.py#L89).

Let's resolve this by using `img_shape: Tuple[int, int]` throughout the code instead of these separate y and x values.
