### ISSUE TITLE
Include additional dataset metadata with `autoregressive_predictions.nc`

### ISSUE THREAD

**Issue by jpdunc23** [ai2cm/ace#170]
It would be good to include the following:

- The time axis. This could be calculated on demand using `xr.cftime_range` by keeping track of the calendar, start time, and step frequency in the data loader.
- Variable units and long names.

**Comment by oliverwm1** [comment]
Variable units and long names are intended to be in the output file (see below). If you're finding that they are not, there may be a bug in getting metadata via the data loader.

https://github.com/ai2cm/full-model/blob/0921ac95ba10a398b0b319bf2281d7ef8afc1f14/fme/fme/fcn_training/inference/data_writer.py#L80-L86

In terms of the time axis, since our netCDF output can contain multiple ensemble members which do not share the same start time, we'll want to keep the "time" axis to be a relative time since the start of the simulation. But then we can have another coordinate for the "sample"/"ensemble" dimension which tracks the start time of each run. (this is typical for datasets of ensemble predictions, e.g. https://climpred.readthedocs.io/en/stable/setting-up-data.html). I don't think this is super high priority, but would be nice.

**Comment by jpdunc23** [comment]
> Variable units and long names are intended to be in the output file

OK, I will look into the metadata further. Maybe I just missed it.

> we'll want to keep the "time" axis to be a relative time since the start of the simulation... I don't think this is super high priority, but would be nice.

Sounds good. Agreed that including the time axis isn't high priority or perhaps necessary at all, but including metadata about the timestep size and the calendar would be easy and helpful for the diagnostics pipeline I'm working on to create sensible time axes without having to specify those values in the config.

**Comment by jpdunc23** [comment]
@oliverwm1, I looked into the metadata and it seems to not be in the nc file:
```
ncdump -h $SCRATCH/ai2/datasets/e3smv2-1deg-gaussian-fme-40yr/output/batch-size-32/lr2.5e-3/autoregressive_predictions.nc 
netcdf autoregressive_predictions {
dimensions:
	source = 2 ;
	timestep = UNLIMITED ; // (2921 currently)
	sample = 1 ;
	lat = 180 ;
	lon = 360 ;
variables:
	string source(source) ;
	float lat(lat) ;
	float lon(lon) ;
	float U_2(source, sample, timestep, lat, lon) ;
		U_2:_FillValue = NaNf ;
	float T_1(source, sample, timestep, lat, lon) ;
		T_1:_FillValue = NaNf ;
        ...
        float surface_precipitation_rate(source, sample, timestep, lat, lon) ;
		surface_precipitation_rate:_FillValue = NaNf ;
	float surface_upward_longwave_flux(source, sample, timestep, lat, lon) ;
		surface_upward_longwave_flux:_FillValue = NaNf ;
}
```

**Comment by oliverwm1** [comment]
Interesting... I have found this to work okay. Differences that come to mind are 1) FV3GFS vs E3SM data, but don't really see why this would matter, or 2) xarray versus netCDF data loader (I think used the latter for the example below).

for example:
```
(fv3net) OliWM@oliwm-vm:~/scratch$ ncdump -h autoregressive_predictions.nc
netcdf autoregressive_predictions {
dimensions:
	source = 2 ;
	timestep = UNLIMITED ; // (501 currently)
	sample = 1 ;
	n_lat = 180 ;
	n_lon = 360 ;
variables:
	string source(source) ;
	float specific_total_water_2(source, sample, timestep, n_lat, n_lon) ;
		specific_total_water_2:_FillValue = NaNf ;
		specific_total_water_2:units = "kg/kg" ;
		specific_total_water_2:long_name = "specific total water level-2" ;
```

**Comment by jpdunc23** [comment]
OK, will take a closer look.

**Comment by oliverwm1** [comment]
FYI I'm working on deleting the netCDF loader to reduce maintenance burden, and indeed this issue seems to be because the xarray loader does not handle the metadata correctly. I can fix.

**Comment by mcgibbon** [comment]
Is this still an issue @oliverwm1 ?

**Comment by oliverwm1** [comment]
The metadata part is resolved. But it would certainly be helpful to have a meaningful time coordinate (first point above). I'll close this and make a more specific issue with what I have in mind.
