### ISSUE TITLE
Make dry air mass conservation asserts consistent with other dry air computations which are in Pa.

### ISSUE THREAD

**Issue by gideonite** [ai2cm/ace#186]
It seems like a part of the data processing involves checking dry air mass. Meanwhile in one step and full inference, we compute dry air in units of pressure. Should we make this consistent?

See this code: https://github.com/ai2cm/full-model/blob/982be3a356832983f961afe2608b7ecbf532e7d3/projects/data_process/compute_dataset_fv3gfs.py#L311-L333

**Comment by gideonite** [comment]
Would be great if you could weigh in here @oliverwm1 @mcgibbon

**Comment by mcgibbon** [comment]
It looks like this is already using Pa as its unit, despite saying `mass` in the variable name. You could update each instance of `mass` inside the function (and only inside - the title is good as-is) to say `pressure` instead, but I don't mind leaving it either.

The public API of this routine is to assert that global dry air mass is conserved, and the units used internally to do that aren't publicly exposed, so I think it's fine if it used a different measurement of dry air mass than our diagnostic/wandb code. But it does look like it uses Pa and so the units will be consistent anyways.

**Comment by oliverwm1** [comment]
I would echo @mcgibbon. As the print out states, it is computing something in units of Pa:

https://github.com/ai2cm/full-model/blob/982be3a356832983f961afe2608b7ecbf532e7d3/projects/data_process/compute_dataset_fv3gfs.py#L326

The docstring is also explicit about this. The variable/function name is arguably a bit misleading, but it is actually fairly common to use "mass" and "pressure" somewhat interchangeably. As an example, in our coarse-graining work we often talk about "mass weighted averaging". In practice, we do this by actually using the pressure thickness as our weight, since this gives the equivalent result—mass and pressure thickness being related by a constant factor.

Anyway, I don't think there's any need for a change here.
