### ISSUE TITLE
Add time information to videos

### ISSUE THREAD

**Issue by brianhenn** [ai2cm/ace#211]
The wandb videos would be easier to interpret if they indicated the time somehow as they progressed. Presumably lead time would be displayed, following the suggestion in ai2cm/ace-internal-test#155 .

**Comment by oliverwm1** [comment]
We could also just use the step instead of an actual lead time. This would be more similar to the x-axis on our other time/step-dependent metrics.

More generally, I've been a bit hesitant to log custom plots to wandb because of the desire to avoid low level plotting code in our training/inference code. If there is a way to still use wandb.Video and to encode the time/step/frame somehow, that would be most appealing.

**Comment by brianhenn** [comment]
Closing this due to lack of urgency given that we don't look at videos much.
