### ISSUE TITLE
Feature: save best-inference checkpoint

### ISSUE THREAD

**Issue by mcgibbon** [ai2cm/ace#234]
Since we want models with the lowest inference loss, it would be good to have access to the model checkpoint with the smallest inline inference error.

This would require formulating the "loss" for the best inference checkpoint (possibly variable-mean of global mean normalized time-mean RMSEs).

**Comment by oliverwm1** [comment]
Related: ai2cm/ace#231

**Comment by gideonite** [comment]
I'm worried this could lead to overfitting but I guess we are already selecting models based on validation data.

**Comment by mcgibbon** [comment]
We could confirm this again, but in my experience variability of inference performance across samples is much smaller than variability of performance across models, i.e. we don't need to run inference on many examples to tell if that model generalizes well.

**Comment by gideonite** [comment]
I think this is a longer discussion regarding over-fitting which I would be happy to have but probably shouldn't take place here. For the time being, making this change will not change the fact that we don't have a held out set. I was bringing this up because it seemed like this was an opportunity to discuss this again but I realize now that it's out of scope.
