### ISSUE TITLE
Include zonal spectra in core

### ISSUE THREAD

**Issue by gideonite** [ai2cm/ace#262]
This would be useful to have in core—but I am fine to merge here first.

_Originally posted by @oliverwm1 in https://github.com/ai2cm/full-model/pull/492#discussion_r1465725282_

**Comment by oliverwm1** [comment]
We have spectra computed via the spherical harmonic transform (which are computed from global maps instead of only representing variability in zonal direction) in core. So I am going to close this since it has been superseded.

https://github.com/ai2cm/full-model/blob/main/fme/fme/core/aggregator/inference/spectrum.py
