### ISSUE TITLE
feature: add per-variable loss weighting capability

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#295]
We would like to be able to weight different variables in the loss function. This way we won't have to effectively do this through our normalization strategy, which is a bit confusing.

Two options:
1. read per-variable loss weight from a netCDF file on disk
2. specify loss weights in yaml config

Either way, we should have a default of "1" for any variables that don't have a weighting specified.

It would be good to implement this in a way that is decoupled from the choice of loss function (MSE, area-weighted MSE etc.). Perhaps can just multiply the "unpacked + normalized" version of the prediction/target data by the appropriate weightings before passing them into the loss function.

**Comment by mcgibbon** [comment]
Given we mainly plan to use this to make changes to the weighting of a small set of variables (possibly only specific_total_water_0), I'd prefer the yaml config route, since it's easier to test multiple options. If we instead wanted to use this so we can full-field scale the model variables but residual-weight the losses, I'd prefer the netCDF route. If we do this netCDF route, I'd suggest the scales are applied to denormalized values, so we can calculate the weights as we calculate stds and use the same weight netCDF with different ways of normalizing the data.

We could also allow both, with the yaml weights multiplied by the netCDF weights when both are given.

**Comment by oliverwm1** [comment]
> If we instead wanted to use this so we can full-field scale the model variables but residual-weight the losses

This is the feature I was imagining wanting to be able to use this for (we were discussing this at the Monday sync this week).

**Comment by oliverwm1** [comment]
> If we do this netCDF route, I'd suggest the scales are applied to denormalized values

Not sure I follow. If these are loss function weightings, shouldn't they operate on normalized data? I think it would make it a lot clearer what the meaning of the values is if they are unitless.

**Comment by mcgibbon** [comment]
> > If we do this netCDF route, I'd suggest the scales are applied to denormalized values
> 
> Not sure I follow. If these are loss function weightings, shouldn't they operate on normalized data? I think it would make it a lot clearer what the meaning of the values is if they are unitless.

Normalized how? Dimensionless values still have units, which can be more confusing in meaning.

If we want the loss to be residual scaled, it feels more obvious that the weight would be 1/(residual scale), rather than (full field scale)/(residual scale). In other words, it’s clearer to say “the loss is weighted by the residual scale factors” than “the full field normalized loss is weighted by the ratio of the full field and residual scale factors so that the result is scaled according to the residual scale factors”. We can still implement it this way under the hood by dividing the scales, but I think both the normalization and the loss scale should be specified in physical units to be clear.

What happens when you change the nn scaling file but don’t change the loss scaling file?

**Comment by mcgibbon** [comment]
Ah I think I understand a bit the motivation for unitless weights, I'm mixing up weights and scales. While loss weights of the kind "treat these variables with this much importance" should be unitless, I don't think we should use this concept to encode the "scaling" of the loss.

I'd propose that we use a netCDF file to specify the loss scaling/normalization the same way we use it to specify the nn scaling/normalization. In the code we could do the rescaling directly, by dividing these scales, though it will give the same result to do (value * full_scale) / residual_scale or value * (full_scale / residual_scale).

I'd also propose that to do "weighting" of the variables (e.g. to say not to worry so much about upper level humidity), we don't use the netCDF file but instead use yaml config. You're right that this concept is better unitless. Then we can multiply this unitless weighting with the loss-normalized values.

**Comment by AnnaKwa** [comment]
@mcgibbon @oliverwm1 This is my understanding of what we're going for- let me know if there's any misunderstanding. 

- residual vs. full field 'scaling' of variables: use or don't use the residual scaling that currently occurs in the stats data calculation. Scalings saved in the stats dataset lead to the inputs being O(1) after normalization.
- loss weighting: occurs in the loss function, for specified outputs multiply their loss contribution by weight.

Implementation-wise, it would work like so:
- Save both full field scaling and residual scalings in the stats netcdf dataset. The full field scaling is always used for normalization of inputs. 
- To weight all variables by residuals there could be an optional flag in the loss config , which uses residual scalings saved in the netcdf to weight the loss. The default can be set to True keep the same-ish behavior as now.
- Additional weighting of individual variables  in the loss can be set in a yaml.

Let me know if this sounds like / does not sound like what you had in mind.

**Comment by mcgibbon** [comment]
> Save both full field scaling and residual scalings in the stats netcdf dataset. The full field scaling is always used for normalization of inputs.

I believe this is already done, fortunately :)

> To weight all variables by residuals there could be an optional flag in the loss config , which uses residual scalings saved in the netcdf to weight the loss. The default can be set to True keep the same-ish behavior as now.

Yes, specifically an argument where you give file paths to normalization/stats files to specify the loss normalization. If given, the data would be rescaled before giving it to the loss. If not given, the loss would use the same scaling used by the NN (current behavior).

> Additional weighting of individual variables in the loss can be set in a yaml.

Sounds right.

**Comment by oliverwm1** [comment]
Thanks for the summary Anna. I agree on this strategy (originally I thought the residual scaling should be implemented differently, but I've come around to @mcgibbon's suggestion).

I suggest implementing the loss residual scaling feature in a separate PR as the "weighting of individual variables" feature in order to keep the reviewing easier.
