### ISSUE TITLE
Time-mean `column_moist_static_energy_tendency` is NaN

### ISSUE THREAD

**Issue by spencerkclark** [ai2cm/ace#394]
When computing the column moist static energy tendency, computing a finite difference in time is required, which truncates the time dimension of a tensor by one.  A fill value is therefore required to restore the full shape.  I naively suggested NaN, but this leads to NaNs when taking time means (e.g. [here](https://wandb.ai/ai2cm/ace/reports/inference-time_mean-gen_map-column_moist_static_energy_tendency-24-07-15-10-08-56---Vmlldzo4NjgwMzIx)), since we use `mean` instead of `nanmean` when computing metrics internally.  We may need to either consider a different fill value, or switching to `nanmean` when computing these metrics.

xref: https://github.com/ai2cm/full-model/pull/959#discussion_r1674642556

**Comment by AnnaKwa** [comment]
Switching to use nanmean might be useful if we decide to merge any metrics that use masked data in the future (I ran into this on a side branch that had metrics over land). Unless there are any potential issues with doing so I'll do that, if anyone raises an objection I can revert to filling step 0 with the step 1 value.

**Comment by AnnaKwa** [comment]
Weird, my attempt to reproduce the issue in an interactive job did not have the NaN issue: https://wandb.ai/ai2cm/ace-debugging/runs/kgrvarmi/workspace?nw=qeyvccpyq5

**Comment by AnnaKwa** [comment]
I'm not sure why I'm not able to reproduce this locally, but I'm going to just change the initial fill value to 0 rather than change the time means to use `nanmean`, since sometimes the nan is due to the model being unstable and it'd be nice to keep the behavior the same. This approach is similar to what the existing [derived](https://github.com/ai2cm/full-model/blob/bc6c840aa18a69b8ec5888aaec82793880de0885/fme/fme/ace/inference/derived_variables.py#L88) variable for total_water_path_budget_residual does for the first value.

**Comment by spencerkclark** [comment]
Makes sense—thanks @AnnaKwa!  Good to be consistent with the precedent of the `total_water_path_budget_residual` variable and preserve meaningful NaNs when the model crashes.
