### ISSUE TITLE
Evaluator runs spend majority of time uploading wandb metrics

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#417]
Evaluator runs (in particular with a single initial condition) running on jupiter spend the majority of their time uploading wandb metrics. This is not a good use of GPU resources! And it means it takes much longer to get results, and increases possibility of preemption.

For example ([wandb run](https://wandb.ai/ai2cm/ace2/runs/q0ozc0o2/system)) takes about 1.5 hours for doing the actual run, and then about 3 hours for uploading metrics!

<img width="836" alt="Screenshot 2024-08-11 at 6 47 31 PM" src="https://github.com/user-attachments/assets/64b7f106-8794-4a34-be66-e6146317442b">

Possible ideas to improve (I think doing both of the first two would at least nearly resolve the issue):
- reduce # of time-dependent metrics. In particular, I don't think we need to log time-dependent normalized metrics since these can be derived from the regular ones. Specifically, `inference/mean_norm/weighted_bias`, `inference/mean_norm/weighted_mean_gen`, `inference_mean_norm/weighted_mean_target`, `inference/mean_norm/weighted_rmse`, `inference/mean_norm/weighted_std_gen`
- log metrics during the run so the upload can happen in parallel. See ai2cm/ace#192 
- only log every N steps (would prefer to avoid this if possible)

**Comment by mcgibbon** [comment]
Using the wandb core backend (https://github.com/ai2cm/full-model/pull/1022) may help with this.

**Comment by jpdunc23** [comment]
> Using the wandb core backend (#1022) may help with this.

See [this wandb run](https://wandb.ai/ai2cm/jamesd-dev/runs/5hb9epkt/overview) which uses the `jeremym/fme-887e6381` image from ai2cm/full-model#1022, but otherwise uses the same inference config as Oli's run linked above. Sadly, GPU util metrics weren't tracked due to what I think is an issue with wandb not seeing the GPU in shared computing environments, but using wandb-core seems to have reduced the total time for the inference run from 4.25 to 3 hrs.
