### ISSUE TITLE
Training fails on validation step

### ISSUE THREAD

**Issue by brianhenn** [ai2cm/ace#496]
See beaker experiment on a recent commit on main (c74ce5f9): https://beaker.allen.ai/orgs/ai2/workspaces/ace/work/01JD0Z57Q7H3GARXQE5QH5RW13?taskId=01JD0Z57QC30F30PS9654NZ975&jobId=01JD0Z57WAZ6REWRC6ZW3PX6MB

The CPU vs GPU error re: the sigma coordinates appears on the validation step (I think maybe at the first time that computing the derived variables occurs).

**Comment by rebassoo** [comment]
Similar issue on perlmutter with commit from last Friday [d5e8ac97]
  ```
 pressure_thickness = ((ak + (surface_pressure.unsqueeze(-1) * bk))).diff(
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

**Comment by brianhenn** [comment]
For reference this commit is after the [fix](https://github.com/ai2cm/full-model/pull/1322/commits/6d27f576286b8bf43858e719d86dea771b9f1c36) pushed for a similar [issue](https://github.com/ai2cm/ace/issues/482), though in that case the error occurred on data loader initialization and caused a lower-level CUDA error, whereas here it happens after the batches are loaded and triggers an explicit CPU vs GPU complaint when computations are done on some of their data.

Seems like now we need to move the coordinate information to GPU at whatever the appropriate time would be. Does not seem like this was caught by CPU vs GPU typing.

**Comment by mcgibbon** [comment]
Yeah, the device typing only applies to BatchData and not to the coordinates.

I think we should update the code so that everything in the data loading has the coordinates on CPU, except that the objects exposed by GriddedData (including its GriddedOperations) are all on the device, whether done on init or transferred at access time. This should resolve most of these issues.

I should also make a PR removing `derive_func` from BatchData again, keeping it on the stepper. I think that may be needed to resolve this particular issue.

**Comment by brianhenn** [comment]
> except that the objects exposed by GriddedData (including its GriddedOperations) are all on the device, whether done on init or transferred at access time.

This seems like a reasonable approach.

**Comment by brianhenn** [comment]
This could be fixed very simply by sending the sigma coordinates to `device` somewhere in the long chain between initializing the validation data loader and actually recording a batch in the validata aggregator; it's not obvious to me where would be the best place, since this computation is kind of a one-off.

As a result I am leaning towards [moving the computation of dry air mass tendency to the derived variables](https://github.com/ai2cm/ace/issues/498), which would resolve this issue and simply things IMO.

**Comment by brianhenn** [comment]
Also added a failing test that covers this bug (https://github.com/ai2cm/full-model/pull/1368) in the meantime.

**Comment by mcgibbon** [comment]
> it's not obvious to me where would be the best place, since this computation is kind of a one-off.

There are many options but I would suggest where it gets exposed by GriddedData, either in its property method or when GriddedData is initialized. This seems like one that could be easiest to remember, because it's only the internals before this that ever need CPU memory. Then it's _only_ code in `core/data_loading` that ever has to worry about this, because its public methods that return data will return device data.
