### ISSUE TITLE
`inference/annual` metrics are no longer logged to WandB

### ISSUE THREAD

**Issue by spencerkclark** [ai2cm/ace#497]
It appears that since https://github.com/ai2cm/full-model/pull/1345 was merged, `inference/annual` metrics are no longer logged to WandB.  Compare these two WandB runs, which are identical except one uses an image as of `5190f64` (the commit before https://github.com/ai2cm/full-model/pull/1345) and one uses an image as of `d5e8ac9` (the commit of ai2cm/full-model#1345):

- [WandB run with `5190f64`](https://wandb.ai/ai2cm/ace-som/runs/ww5l5ysk)
- [WandB run with `d5e8ac9`](https://wandb.ai/ai2cm/ace-som/runs/fxvshfjg)

cc: @mcgibbon

**Comment by mcgibbon** [comment]
Thanks for catching this - should be resolved by https://github.com/ai2cm/full-model/pull/1388 (which I wrote just now). Testing this is difficult because we need >2yr of data for the annual aggregator to be triggered, and >5yr of data for ENSO. It isn't tested but this is almost certainly fixing the reason this happened in that PR.

I'm guessing the `enso_coefficient` results are also not being recorded to wandb right now.

**Comment by spencerkclark** [comment]
Makes sense—thanks @mcgibbon!
