### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by gideonite** [ai2cm/ace#71]
From our one month plan doc:

![Image](https://user-images.githubusercontent.com/2163686/231874360-4eb71ffe-3faf-4015-92ae-d6a5ec86257f.png)

**Comment by gideonite** [comment]
200hPa temperature, surface precip rate, and precip water are missing from the current variable set. @oliverwm1 

The current variable set is:
```
['UGRD10m', 'VGRD10m', 'TMP2m', 'PRESsfc', 'PRMSL', 'TMP850', 'UGRD1000', 'VGRD1000', 'h1000', 'UGRD850', 'VGRD850', 'h850', 'UGRD500', 'VGRD500', 'h500', 'TMP500', 'h50', 'RH500', 'RH850', 'TCWV']
```

**Comment by gideonite** [comment]
Correct me if I'm wrong:

mean bias is:
```
(ground_truth - predicted).mean()
```
where for time mean bias, the mean is *not* taken over time.

Global RMSE of the time mean is as follows. The idea is to take the time mean of the variables first, then compute the RMSE between these two time-series (thereby summing over time).
```
RMSE(
  ground_truth.mean(("grid_yt", "grid_xt")), predicted.mean(("grid_yt", "grid_xt")))
```

**Comment by oliverwm1** [comment]
Given some global averaging operator A(.) and time-averaging operator T(.), we have

## global-mean and time-mean bias

`A(T(predicted - truth))`

Note: order of means doesn't matter, but it is important that we do prediction minus truth, instead of opposite.

## RMSE of time-mean

`sqrt(A{[T(predicted) - T(truth)]**2})`

This is a bit different than what you have above. First want to compute a time-average of the each field and take difference (or take difference and do time-average of that). Then compute an RMSE over x/y. 

Note that the global averaging operator `A` should be area-weighted. You can see the existing code in FourCastNet to compute the spatial RMSE here: https://github.com/ai2cm/full-model/blob/5708f2d4a4b9f5708680316a7cecea650393ecfd/models/FourCastNet/utils/weighted_acc_rmse.py#L149

**Comment by gideonite** [comment]
This is super helpful, thanks Oli. I'm going through the FCN code and it's a bit gnarly. I like your version much better. How about I adapt this a bit to our use cases? https://github.com/ai2cm/explore/blob/master/oliwm/2023-04-16-fme-analysis/2023-04-16-moisture-conservation.ipynb

**Comment by oliverwm1** [comment]
I think that's fine, although it can be tricky to get code that works for a wide variety of use cases (e.g. during training/validation and also during notebook analysis etc) since we may use different data structures in different contexts. I would focus on implementing metrics that we will use during validation—i.e. make sure they work with pytorch tensors.

**Comment by gideonite** [comment]
In the interest of keeping things moving, I think it's ok to mark this as completed. The next step is ai2cm/ace#84.

**Comment by oliverwm1** [comment]
Agreed we can close this and use ai2cm/ace#84 to track implementation in inference code.
